### PR TITLE
Fix fetching Bilibili cookie to #82

### LINKED ISSUE #82: Bilibili search api needs cookie now
image

Bilibili starts checking cookie info in search api since 8/24. We need to get cookie for requesting.

### PR DESCRIPTION
**Pull request by maoqxxmm**
Fetch and store Bilibili cookie at initialization or before search. The cookie will expire after 1 year. So refreshing it at the startup is enough.

fixed #82

### CODE REVIEW

File: server/models/mv/bilibili/provider.js [hunk 1]
```diff
@@ -2,15 +2,41 @@ import fetch from "node-fetch";
 import Entry, { NAME } from "./entry";
 
 class Provider {
+  cookie;
+
+  constructor() {
+    // TODO: It's async but should work most time.
+    this._initCookie();
```
Comment (zhxie) [inline server/models/mv/bilibili/provider.js:9]: I think there will be racing between the async init and init on searching.
Let us remove it and only initialize cookies on the first searching.

**Review by zhxie — CHANGES_REQUESTED** [review]

File: server/models/mv/bilibili/provider.js (hunk 1 above)
Comment (maoqxxmm) [reply server/models/mv/bilibili/provider.js:9]: Ok, that's reasonable.

Comment (maoqxxmm) [reply server/models/mv/bilibili/provider.js]: Done

**Review by zhxie — APPROVED** [review]
